// Code generated by ent, DO NOT EDIT.

package usersettings

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the usersettings type in the database.
	Label = "user_settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTheme holds the string denoting the theme field in the database.
	FieldTheme = "theme"
	// FieldEmailNotifications holds the string denoting the email_notifications field in the database.
	FieldEmailNotifications = "email_notifications"
	// FieldBrowserNotifications holds the string denoting the browser_notifications field in the database.
	FieldBrowserNotifications = "browser_notifications"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldSessionTimeoutMinutes holds the string denoting the session_timeout_minutes field in the database.
	FieldSessionTimeoutMinutes = "session_timeout_minutes"
	// FieldAutoSummarize holds the string denoting the auto_summarize field in the database.
	FieldAutoSummarize = "auto_summarize"
	// FieldExtensionSettings holds the string denoting the extension_settings field in the database.
	FieldExtensionSettings = "extension_settings"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the usersettings in the database.
	Table = "user_settings"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_settings"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_settings"
)

// Columns holds all SQL columns for usersettings fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTheme,
	FieldEmailNotifications,
	FieldBrowserNotifications,
	FieldLanguage,
	FieldSessionTimeoutMinutes,
	FieldAutoSummarize,
	FieldExtensionSettings,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "user_settings"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_settings",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultEmailNotifications holds the default value on creation for the "email_notifications" field.
	DefaultEmailNotifications bool
	// DefaultBrowserNotifications holds the default value on creation for the "browser_notifications" field.
	DefaultBrowserNotifications bool
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
	// DefaultSessionTimeoutMinutes holds the default value on creation for the "session_timeout_minutes" field.
	DefaultSessionTimeoutMinutes int
	// DefaultAutoSummarize holds the default value on creation for the "auto_summarize" field.
	DefaultAutoSummarize bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Theme defines the type for the "theme" enum field.
type Theme string

// ThemeSystem is the default value of the Theme enum.
const DefaultTheme = ThemeSystem

// Theme values.
const (
	ThemeLight  Theme = "light"
	ThemeDark   Theme = "dark"
	ThemeSystem Theme = "system"
)

func (t Theme) String() string {
	return string(t)
}

// ThemeValidator is a validator for the "theme" field enum values. It is called by the builders before save.
func ThemeValidator(t Theme) error {
	switch t {
	case ThemeLight, ThemeDark, ThemeSystem:
		return nil
	default:
		return fmt.Errorf("usersettings: invalid enum value for theme field: %q", t)
	}
}

// OrderOption defines the ordering options for the UserSettings queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTheme orders the results by the theme field.
func ByTheme(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTheme, opts...).ToFunc()
}

// ByEmailNotifications orders the results by the email_notifications field.
func ByEmailNotifications(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailNotifications, opts...).ToFunc()
}

// ByBrowserNotifications orders the results by the browser_notifications field.
func ByBrowserNotifications(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrowserNotifications, opts...).ToFunc()
}

// ByLanguage orders the results by the language field.
func ByLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguage, opts...).ToFunc()
}

// BySessionTimeoutMinutes orders the results by the session_timeout_minutes field.
func BySessionTimeoutMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionTimeoutMinutes, opts...).ToFunc()
}

// ByAutoSummarize orders the results by the auto_summarize field.
func ByAutoSummarize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoSummarize, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
	)
}
