// Code generated by ent, DO NOT EDIT.

package session

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the session type in the database.
	Label = "session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSessionStatus holds the string denoting the session_status field in the database.
	FieldSessionStatus = "session_status"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgePageVisits holds the string denoting the page_visits edge name in mutations.
	EdgePageVisits = "page_visits"
	// EdgeHighlights holds the string denoting the highlights edge name in mutations.
	EdgeHighlights = "highlights"
	// EdgeRawEvents holds the string denoting the raw_events edge name in mutations.
	EdgeRawEvents = "raw_events"
	// EdgeMindmap holds the string denoting the mindmap edge name in mutations.
	EdgeMindmap = "mindmap"
	// EdgeTokenUsage holds the string denoting the token_usage edge name in mutations.
	EdgeTokenUsage = "token_usage"
	// EdgeAiLogs holds the string denoting the ai_logs edge name in mutations.
	EdgeAiLogs = "ai_logs"
	// Table holds the table name of the session in the database.
	Table = "sessions"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "sessions"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_sessions"
	// PageVisitsTable is the table that holds the page_visits relation/edge.
	PageVisitsTable = "page_visits"
	// PageVisitsInverseTable is the table name for the PageVisit entity.
	// It exists in this package in order to avoid circular dependency with the "pagevisit" package.
	PageVisitsInverseTable = "page_visits"
	// PageVisitsColumn is the table column denoting the page_visits relation/edge.
	PageVisitsColumn = "session_page_visits"
	// HighlightsTable is the table that holds the highlights relation/edge.
	HighlightsTable = "highlights"
	// HighlightsInverseTable is the table name for the Highlight entity.
	// It exists in this package in order to avoid circular dependency with the "highlight" package.
	HighlightsInverseTable = "highlights"
	// HighlightsColumn is the table column denoting the highlights relation/edge.
	HighlightsColumn = "session_highlights"
	// RawEventsTable is the table that holds the raw_events relation/edge.
	RawEventsTable = "raw_events"
	// RawEventsInverseTable is the table name for the RawEvent entity.
	// It exists in this package in order to avoid circular dependency with the "rawevent" package.
	RawEventsInverseTable = "raw_events"
	// RawEventsColumn is the table column denoting the raw_events relation/edge.
	RawEventsColumn = "session_raw_events"
	// MindmapTable is the table that holds the mindmap relation/edge.
	MindmapTable = "mindmap_graphs"
	// MindmapInverseTable is the table name for the MindmapGraph entity.
	// It exists in this package in order to avoid circular dependency with the "mindmapgraph" package.
	MindmapInverseTable = "mindmap_graphs"
	// MindmapColumn is the table column denoting the mindmap relation/edge.
	MindmapColumn = "session_mindmap"
	// TokenUsageTable is the table that holds the token_usage relation/edge.
	TokenUsageTable = "token_usages"
	// TokenUsageInverseTable is the table name for the TokenUsage entity.
	// It exists in this package in order to avoid circular dependency with the "tokenusage" package.
	TokenUsageInverseTable = "token_usages"
	// TokenUsageColumn is the table column denoting the token_usage relation/edge.
	TokenUsageColumn = "session_token_usage"
	// AiLogsTable is the table that holds the ai_logs relation/edge.
	AiLogsTable = "ai_logs"
	// AiLogsInverseTable is the table name for the AILog entity.
	// It exists in this package in order to avoid circular dependency with the "ailog" package.
	AiLogsInverseTable = "ai_logs"
	// AiLogsColumn is the table column denoting the ai_logs relation/edge.
	AiLogsColumn = "session_id"
)

// Columns holds all SQL columns for session fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldStatus,
	FieldDeletedAt,
	FieldTitle,
	FieldDescription,
	FieldSessionStatus,
	FieldStartedAt,
	FieldEndedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "sessions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_sessions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultStartedAt holds the default value on creation for the "started_at" field.
	DefaultStartedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusInactive Status = "inactive"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusInactive:
		return nil
	default:
		return fmt.Errorf("session: invalid enum value for status field: %q", s)
	}
}

// SessionStatus defines the type for the "session_status" enum field.
type SessionStatus string

// SessionStatusRecording is the default value of the SessionStatus enum.
const DefaultSessionStatus = SessionStatusRecording

// SessionStatus values.
const (
	SessionStatusRecording  SessionStatus = "recording"
	SessionStatusPaused     SessionStatus = "paused"
	SessionStatusProcessing SessionStatus = "processing"
	SessionStatusCompleted  SessionStatus = "completed"
	SessionStatusFailed     SessionStatus = "failed"
)

func (ss SessionStatus) String() string {
	return string(ss)
}

// SessionStatusValidator is a validator for the "session_status" field enum values. It is called by the builders before save.
func SessionStatusValidator(ss SessionStatus) error {
	switch ss {
	case SessionStatusRecording, SessionStatusPaused, SessionStatusProcessing, SessionStatusCompleted, SessionStatusFailed:
		return nil
	default:
		return fmt.Errorf("session: invalid enum value for session_status field: %q", ss)
	}
}

// OrderOption defines the ordering options for the Session queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// BySessionStatus orders the results by the session_status field.
func BySessionStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionStatus, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByEndedAt orders the results by the ended_at field.
func ByEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByPageVisitsCount orders the results by page_visits count.
func ByPageVisitsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPageVisitsStep(), opts...)
	}
}

// ByPageVisits orders the results by page_visits terms.
func ByPageVisits(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPageVisitsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByHighlightsCount orders the results by highlights count.
func ByHighlightsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newHighlightsStep(), opts...)
	}
}

// ByHighlights orders the results by highlights terms.
func ByHighlights(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHighlightsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRawEventsCount orders the results by raw_events count.
func ByRawEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRawEventsStep(), opts...)
	}
}

// ByRawEvents orders the results by raw_events terms.
func ByRawEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRawEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMindmapField orders the results by mindmap field.
func ByMindmapField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMindmapStep(), sql.OrderByField(field, opts...))
	}
}

// ByTokenUsageCount orders the results by token_usage count.
func ByTokenUsageCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTokenUsageStep(), opts...)
	}
}

// ByTokenUsage orders the results by token_usage terms.
func ByTokenUsage(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTokenUsageStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAiLogsCount orders the results by ai_logs count.
func ByAiLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAiLogsStep(), opts...)
	}
}

// ByAiLogs orders the results by ai_logs terms.
func ByAiLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAiLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newPageVisitsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PageVisitsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PageVisitsTable, PageVisitsColumn),
	)
}
func newHighlightsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HighlightsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, HighlightsTable, HighlightsColumn),
	)
}
func newRawEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RawEventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RawEventsTable, RawEventsColumn),
	)
}
func newMindmapStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MindmapInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, MindmapTable, MindmapColumn),
	)
}
func newTokenUsageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TokenUsageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TokenUsageTable, TokenUsageColumn),
	)
}
func newAiLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AiLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AiLogsTable, AiLogsColumn),
	)
}
