// Code generated by ent, DO NOT EDIT.

package pagevisit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the pagevisit type in the database.
	Label = "page_visit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldEnteredAt holds the string denoting the entered_at field in the database.
	FieldEnteredAt = "entered_at"
	// FieldLeftAt holds the string denoting the left_at field in the database.
	FieldLeftAt = "left_at"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldMaxScrollDepth holds the string denoting the max_scroll_depth field in the database.
	FieldMaxScrollDepth = "max_scroll_depth"
	// EdgeSession holds the string denoting the session edge name in mutations.
	EdgeSession = "session"
	// EdgeURL holds the string denoting the url edge name in mutations.
	EdgeURL = "url"
	// Table holds the table name of the pagevisit in the database.
	Table = "page_visits"
	// SessionTable is the table that holds the session relation/edge.
	SessionTable = "page_visits"
	// SessionInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	SessionInverseTable = "sessions"
	// SessionColumn is the table column denoting the session relation/edge.
	SessionColumn = "session_page_visits"
	// URLTable is the table that holds the url relation/edge.
	URLTable = "page_visits"
	// URLInverseTable is the table name for the URL entity.
	// It exists in this package in order to avoid circular dependency with the "url" package.
	URLInverseTable = "ur_ls"
	// URLColumn is the table column denoting the url relation/edge.
	URLColumn = "page_visit_url"
)

// Columns holds all SQL columns for pagevisit fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldEnteredAt,
	FieldLeftAt,
	FieldDurationMs,
	FieldMaxScrollDepth,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "page_visits"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"page_visit_url",
	"session_page_visits",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultEnteredAt holds the default value on creation for the "entered_at" field.
	DefaultEnteredAt func() time.Time
	// DefaultMaxScrollDepth holds the default value on creation for the "max_scroll_depth" field.
	DefaultMaxScrollDepth float64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the PageVisit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEnteredAt orders the results by the entered_at field.
func ByEnteredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnteredAt, opts...).ToFunc()
}

// ByLeftAt orders the results by the left_at field.
func ByLeftAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeftAt, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByMaxScrollDepth orders the results by the max_scroll_depth field.
func ByMaxScrollDepth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxScrollDepth, opts...).ToFunc()
}

// BySessionField orders the results by session field.
func BySessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionStep(), sql.OrderByField(field, opts...))
	}
}

// ByURLField orders the results by url field.
func ByURLField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newURLStep(), sql.OrderByField(field, opts...))
	}
}
func newSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
	)
}
func newURLStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(URLInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, URLTable, URLColumn),
	)
}
