run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/mindhit

issues:
  exclude-use-default: false
  exclude-rules:
    - path: ent/schema/
      linters:
        - revive
    - path: internal/generated/
      linters:
        - revive
