// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mindhit/api/ent/ailog"
	"github.com/mindhit/api/ent/predicate"
	"github.com/mindhit/api/ent/session"
	"github.com/mindhit/api/ent/user"
)

// AILogUpdate is the builder for updating AILog entities.
type AILogUpdate struct {
	config
	hooks    []Hook
	mutation *AILogMutation
}

// Where appends a list predicates to the AILogUpdate builder.
func (_u *AILogUpdate) Where(ps ...predicate.AILog) *AILogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AILogUpdate) SetUserID(v uuid.UUID) *AILogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableUserID(v *uuid.UUID) *AILogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AILogUpdate) ClearUserID() *AILogUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AILogUpdate) SetSessionID(v uuid.UUID) *AILogUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableSessionID(v *uuid.UUID) *AILogUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *AILogUpdate) ClearSessionID() *AILogUpdate {
	_u.mutation.ClearSessionID()
	return _u
}

// SetTaskType sets the "task_type" field.
func (_u *AILogUpdate) SetTaskType(v string) *AILogUpdate {
	_u.mutation.SetTaskType(v)
	return _u
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableTaskType(v *string) *AILogUpdate {
	if v != nil {
		_u.SetTaskType(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AILogUpdate) SetProvider(v string) *AILogUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableProvider(v *string) *AILogUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AILogUpdate) SetModel(v string) *AILogUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableModel(v *string) *AILogUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *AILogUpdate) SetSystemPrompt(v string) *AILogUpdate {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableSystemPrompt(v *string) *AILogUpdate {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (_u *AILogUpdate) ClearSystemPrompt() *AILogUpdate {
	_u.mutation.ClearSystemPrompt()
	return _u
}

// SetUserPrompt sets the "user_prompt" field.
func (_u *AILogUpdate) SetUserPrompt(v string) *AILogUpdate {
	_u.mutation.SetUserPrompt(v)
	return _u
}

// SetNillableUserPrompt sets the "user_prompt" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableUserPrompt(v *string) *AILogUpdate {
	if v != nil {
		_u.SetUserPrompt(*v)
	}
	return _u
}

// ClearUserPrompt clears the value of the "user_prompt" field.
func (_u *AILogUpdate) ClearUserPrompt() *AILogUpdate {
	_u.mutation.ClearUserPrompt()
	return _u
}

// SetThinking sets the "thinking" field.
func (_u *AILogUpdate) SetThinking(v string) *AILogUpdate {
	_u.mutation.SetThinking(v)
	return _u
}

// SetNillableThinking sets the "thinking" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableThinking(v *string) *AILogUpdate {
	if v != nil {
		_u.SetThinking(*v)
	}
	return _u
}

// ClearThinking clears the value of the "thinking" field.
func (_u *AILogUpdate) ClearThinking() *AILogUpdate {
	_u.mutation.ClearThinking()
	return _u
}

// SetContent sets the "content" field.
func (_u *AILogUpdate) SetContent(v string) *AILogUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableContent(v *string) *AILogUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *AILogUpdate) ClearContent() *AILogUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *AILogUpdate) SetInputTokens(v int) *AILogUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableInputTokens(v *int) *AILogUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *AILogUpdate) AddInputTokens(v int) *AILogUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *AILogUpdate) SetOutputTokens(v int) *AILogUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableOutputTokens(v *int) *AILogUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *AILogUpdate) AddOutputTokens(v int) *AILogUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetThinkingTokens sets the "thinking_tokens" field.
func (_u *AILogUpdate) SetThinkingTokens(v int) *AILogUpdate {
	_u.mutation.ResetThinkingTokens()
	_u.mutation.SetThinkingTokens(v)
	return _u
}

// SetNillableThinkingTokens sets the "thinking_tokens" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableThinkingTokens(v *int) *AILogUpdate {
	if v != nil {
		_u.SetThinkingTokens(*v)
	}
	return _u
}

// AddThinkingTokens adds value to the "thinking_tokens" field.
func (_u *AILogUpdate) AddThinkingTokens(v int) *AILogUpdate {
	_u.mutation.AddThinkingTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *AILogUpdate) SetTotalTokens(v int) *AILogUpdate {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableTotalTokens(v *int) *AILogUpdate {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *AILogUpdate) AddTotalTokens(v int) *AILogUpdate {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *AILogUpdate) SetLatencyMs(v int64) *AILogUpdate {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableLatencyMs(v *int64) *AILogUpdate {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *AILogUpdate) AddLatencyMs(v int64) *AILogUpdate {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AILogUpdate) SetRequestID(v string) *AILogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableRequestID(v *string) *AILogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AILogUpdate) ClearRequestID() *AILogUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AILogUpdate) SetStatus(v ailog.Status) *AILogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableStatus(v *ailog.Status) *AILogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *AILogUpdate) SetErrorMessage(v string) *AILogUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableErrorMessage(v *string) *AILogUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *AILogUpdate) ClearErrorMessage() *AILogUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetEstimatedCostCents sets the "estimated_cost_cents" field.
func (_u *AILogUpdate) SetEstimatedCostCents(v int) *AILogUpdate {
	_u.mutation.ResetEstimatedCostCents()
	_u.mutation.SetEstimatedCostCents(v)
	return _u
}

// SetNillableEstimatedCostCents sets the "estimated_cost_cents" field if the given value is not nil.
func (_u *AILogUpdate) SetNillableEstimatedCostCents(v *int) *AILogUpdate {
	if v != nil {
		_u.SetEstimatedCostCents(*v)
	}
	return _u
}

// AddEstimatedCostCents adds value to the "estimated_cost_cents" field.
func (_u *AILogUpdate) AddEstimatedCostCents(v int) *AILogUpdate {
	_u.mutation.AddEstimatedCostCents(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AILogUpdate) SetMetadata(v map[string]interface{}) *AILogUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AILogUpdate) ClearMetadata() *AILogUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AILogUpdate) SetUser(v *User) *AILogUpdate {
	return _u.SetUserID(v.ID)
}

// SetSession sets the "session" edge to the Session entity.
func (_u *AILogUpdate) SetSession(v *Session) *AILogUpdate {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the AILogMutation object of the builder.
func (_u *AILogUpdate) Mutation() *AILogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AILogUpdate) ClearUser() *AILogUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *AILogUpdate) ClearSession() *AILogUpdate {
	_u.mutation.ClearSession()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AILogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AILogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AILogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AILogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AILogUpdate) check() error {
	if v, ok := _u.mutation.TaskType(); ok {
		if err := ailog.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "AILog.task_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := ailog.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AILog.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := ailog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AILog.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ailog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AILog.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AILogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ailog.Table, ailog.Columns, sqlgraph.NewFieldSpec(ailog.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskType(); ok {
		_spec.SetField(ailog.FieldTaskType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(ailog.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(ailog.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(ailog.FieldSystemPrompt, field.TypeString, value)
	}
	if _u.mutation.SystemPromptCleared() {
		_spec.ClearField(ailog.FieldSystemPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.UserPrompt(); ok {
		_spec.SetField(ailog.FieldUserPrompt, field.TypeString, value)
	}
	if _u.mutation.UserPromptCleared() {
		_spec.ClearField(ailog.FieldUserPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.Thinking(); ok {
		_spec.SetField(ailog.FieldThinking, field.TypeString, value)
	}
	if _u.mutation.ThinkingCleared() {
		_spec.ClearField(ailog.FieldThinking, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(ailog.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(ailog.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(ailog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(ailog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(ailog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(ailog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ThinkingTokens(); ok {
		_spec.SetField(ailog.FieldThinkingTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedThinkingTokens(); ok {
		_spec.AddField(ailog.FieldThinkingTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(ailog.FieldTotalTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(ailog.FieldTotalTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(ailog.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(ailog.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(ailog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(ailog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ailog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(ailog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(ailog.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.EstimatedCostCents(); ok {
		_spec.SetField(ailog.FieldEstimatedCostCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedCostCents(); ok {
		_spec.AddField(ailog.FieldEstimatedCostCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(ailog.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(ailog.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ailog.UserTable,
			Columns: []string{ailog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ailog.UserTable,
			Columns: []string{ailog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ailog.SessionTable,
			Columns: []string{ailog.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ailog.SessionTable,
			Columns: []string{ailog.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ailog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AILogUpdateOne is the builder for updating a single AILog entity.
type AILogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AILogMutation
}

// SetUserID sets the "user_id" field.
func (_u *AILogUpdateOne) SetUserID(v uuid.UUID) *AILogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableUserID(v *uuid.UUID) *AILogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AILogUpdateOne) ClearUserID() *AILogUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AILogUpdateOne) SetSessionID(v uuid.UUID) *AILogUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableSessionID(v *uuid.UUID) *AILogUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *AILogUpdateOne) ClearSessionID() *AILogUpdateOne {
	_u.mutation.ClearSessionID()
	return _u
}

// SetTaskType sets the "task_type" field.
func (_u *AILogUpdateOne) SetTaskType(v string) *AILogUpdateOne {
	_u.mutation.SetTaskType(v)
	return _u
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableTaskType(v *string) *AILogUpdateOne {
	if v != nil {
		_u.SetTaskType(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AILogUpdateOne) SetProvider(v string) *AILogUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableProvider(v *string) *AILogUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AILogUpdateOne) SetModel(v string) *AILogUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableModel(v *string) *AILogUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *AILogUpdateOne) SetSystemPrompt(v string) *AILogUpdateOne {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableSystemPrompt(v *string) *AILogUpdateOne {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (_u *AILogUpdateOne) ClearSystemPrompt() *AILogUpdateOne {
	_u.mutation.ClearSystemPrompt()
	return _u
}

// SetUserPrompt sets the "user_prompt" field.
func (_u *AILogUpdateOne) SetUserPrompt(v string) *AILogUpdateOne {
	_u.mutation.SetUserPrompt(v)
	return _u
}

// SetNillableUserPrompt sets the "user_prompt" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableUserPrompt(v *string) *AILogUpdateOne {
	if v != nil {
		_u.SetUserPrompt(*v)
	}
	return _u
}

// ClearUserPrompt clears the value of the "user_prompt" field.
func (_u *AILogUpdateOne) ClearUserPrompt() *AILogUpdateOne {
	_u.mutation.ClearUserPrompt()
	return _u
}

// SetThinking sets the "thinking" field.
func (_u *AILogUpdateOne) SetThinking(v string) *AILogUpdateOne {
	_u.mutation.SetThinking(v)
	return _u
}

// SetNillableThinking sets the "thinking" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableThinking(v *string) *AILogUpdateOne {
	if v != nil {
		_u.SetThinking(*v)
	}
	return _u
}

// ClearThinking clears the value of the "thinking" field.
func (_u *AILogUpdateOne) ClearThinking() *AILogUpdateOne {
	_u.mutation.ClearThinking()
	return _u
}

// SetContent sets the "content" field.
func (_u *AILogUpdateOne) SetContent(v string) *AILogUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableContent(v *string) *AILogUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *AILogUpdateOne) ClearContent() *AILogUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *AILogUpdateOne) SetInputTokens(v int) *AILogUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableInputTokens(v *int) *AILogUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *AILogUpdateOne) AddInputTokens(v int) *AILogUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *AILogUpdateOne) SetOutputTokens(v int) *AILogUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableOutputTokens(v *int) *AILogUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *AILogUpdateOne) AddOutputTokens(v int) *AILogUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetThinkingTokens sets the "thinking_tokens" field.
func (_u *AILogUpdateOne) SetThinkingTokens(v int) *AILogUpdateOne {
	_u.mutation.ResetThinkingTokens()
	_u.mutation.SetThinkingTokens(v)
	return _u
}

// SetNillableThinkingTokens sets the "thinking_tokens" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableThinkingTokens(v *int) *AILogUpdateOne {
	if v != nil {
		_u.SetThinkingTokens(*v)
	}
	return _u
}

// AddThinkingTokens adds value to the "thinking_tokens" field.
func (_u *AILogUpdateOne) AddThinkingTokens(v int) *AILogUpdateOne {
	_u.mutation.AddThinkingTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *AILogUpdateOne) SetTotalTokens(v int) *AILogUpdateOne {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableTotalTokens(v *int) *AILogUpdateOne {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *AILogUpdateOne) AddTotalTokens(v int) *AILogUpdateOne {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *AILogUpdateOne) SetLatencyMs(v int64) *AILogUpdateOne {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableLatencyMs(v *int64) *AILogUpdateOne {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *AILogUpdateOne) AddLatencyMs(v int64) *AILogUpdateOne {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AILogUpdateOne) SetRequestID(v string) *AILogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableRequestID(v *string) *AILogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AILogUpdateOne) ClearRequestID() *AILogUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AILogUpdateOne) SetStatus(v ailog.Status) *AILogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableStatus(v *ailog.Status) *AILogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *AILogUpdateOne) SetErrorMessage(v string) *AILogUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableErrorMessage(v *string) *AILogUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *AILogUpdateOne) ClearErrorMessage() *AILogUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetEstimatedCostCents sets the "estimated_cost_cents" field.
func (_u *AILogUpdateOne) SetEstimatedCostCents(v int) *AILogUpdateOne {
	_u.mutation.ResetEstimatedCostCents()
	_u.mutation.SetEstimatedCostCents(v)
	return _u
}

// SetNillableEstimatedCostCents sets the "estimated_cost_cents" field if the given value is not nil.
func (_u *AILogUpdateOne) SetNillableEstimatedCostCents(v *int) *AILogUpdateOne {
	if v != nil {
		_u.SetEstimatedCostCents(*v)
	}
	return _u
}

// AddEstimatedCostCents adds value to the "estimated_cost_cents" field.
func (_u *AILogUpdateOne) AddEstimatedCostCents(v int) *AILogUpdateOne {
	_u.mutation.AddEstimatedCostCents(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AILogUpdateOne) SetMetadata(v map[string]interface{}) *AILogUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AILogUpdateOne) ClearMetadata() *AILogUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AILogUpdateOne) SetUser(v *User) *AILogUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetSession sets the "session" edge to the Session entity.
func (_u *AILogUpdateOne) SetSession(v *Session) *AILogUpdateOne {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the AILogMutation object of the builder.
func (_u *AILogUpdateOne) Mutation() *AILogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AILogUpdateOne) ClearUser() *AILogUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *AILogUpdateOne) ClearSession() *AILogUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// Where appends a list predicates to the AILogUpdate builder.
func (_u *AILogUpdateOne) Where(ps ...predicate.AILog) *AILogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AILogUpdateOne) Select(field string, fields ...string) *AILogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AILog entity.
func (_u *AILogUpdateOne) Save(ctx context.Context) (*AILog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AILogUpdateOne) SaveX(ctx context.Context) *AILog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AILogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AILogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AILogUpdateOne) check() error {
	if v, ok := _u.mutation.TaskType(); ok {
		if err := ailog.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "AILog.task_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := ailog.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AILog.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := ailog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AILog.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ailog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AILog.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AILogUpdateOne) sqlSave(ctx context.Context) (_node *AILog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ailog.Table, ailog.Columns, sqlgraph.NewFieldSpec(ailog.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AILog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ailog.FieldID)
		for _, f := range fields {
			if !ailog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ailog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskType(); ok {
		_spec.SetField(ailog.FieldTaskType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(ailog.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(ailog.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(ailog.FieldSystemPrompt, field.TypeString, value)
	}
	if _u.mutation.SystemPromptCleared() {
		_spec.ClearField(ailog.FieldSystemPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.UserPrompt(); ok {
		_spec.SetField(ailog.FieldUserPrompt, field.TypeString, value)
	}
	if _u.mutation.UserPromptCleared() {
		_spec.ClearField(ailog.FieldUserPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.Thinking(); ok {
		_spec.SetField(ailog.FieldThinking, field.TypeString, value)
	}
	if _u.mutation.ThinkingCleared() {
		_spec.ClearField(ailog.FieldThinking, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(ailog.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(ailog.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(ailog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(ailog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(ailog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(ailog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ThinkingTokens(); ok {
		_spec.SetField(ailog.FieldThinkingTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedThinkingTokens(); ok {
		_spec.AddField(ailog.FieldThinkingTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(ailog.FieldTotalTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(ailog.FieldTotalTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(ailog.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(ailog.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(ailog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(ailog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ailog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(ailog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(ailog.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.EstimatedCostCents(); ok {
		_spec.SetField(ailog.FieldEstimatedCostCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedCostCents(); ok {
		_spec.AddField(ailog.FieldEstimatedCostCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(ailog.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(ailog.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ailog.UserTable,
			Columns: []string{ailog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ailog.UserTable,
			Columns: []string{ailog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ailog.SessionTable,
			Columns: []string{ailog.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ailog.SessionTable,
			Columns: []string{ailog.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AILog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ailog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
