// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mindhit/api/ent/mindmapgraph"
	"github.com/mindhit/api/ent/predicate"
	"github.com/mindhit/api/ent/session"
)

// MindmapGraphUpdate is the builder for updating MindmapGraph entities.
type MindmapGraphUpdate struct {
	config
	hooks    []Hook
	mutation *MindmapGraphMutation
}

// Where appends a list predicates to the MindmapGraphUpdate builder.
func (_u *MindmapGraphUpdate) Where(ps ...predicate.MindmapGraph) *MindmapGraphUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MindmapGraphUpdate) SetUpdatedAt(v time.Time) *MindmapGraphUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNodes sets the "nodes" field.
func (_u *MindmapGraphUpdate) SetNodes(v []map[string]interface{}) *MindmapGraphUpdate {
	_u.mutation.SetNodes(v)
	return _u
}

// AppendNodes appends value to the "nodes" field.
func (_u *MindmapGraphUpdate) AppendNodes(v []map[string]interface{}) *MindmapGraphUpdate {
	_u.mutation.AppendNodes(v)
	return _u
}

// ClearNodes clears the value of the "nodes" field.
func (_u *MindmapGraphUpdate) ClearNodes() *MindmapGraphUpdate {
	_u.mutation.ClearNodes()
	return _u
}

// SetGraphEdges sets the "graph_edges" field.
func (_u *MindmapGraphUpdate) SetGraphEdges(v []map[string]interface{}) *MindmapGraphUpdate {
	_u.mutation.SetGraphEdges(v)
	return _u
}

// AppendGraphEdges appends value to the "graph_edges" field.
func (_u *MindmapGraphUpdate) AppendGraphEdges(v []map[string]interface{}) *MindmapGraphUpdate {
	_u.mutation.AppendGraphEdges(v)
	return _u
}

// ClearGraphEdges clears the value of the "graph_edges" field.
func (_u *MindmapGraphUpdate) ClearGraphEdges() *MindmapGraphUpdate {
	_u.mutation.ClearGraphEdges()
	return _u
}

// SetLayout sets the "layout" field.
func (_u *MindmapGraphUpdate) SetLayout(v map[string]interface{}) *MindmapGraphUpdate {
	_u.mutation.SetLayout(v)
	return _u
}

// ClearLayout clears the value of the "layout" field.
func (_u *MindmapGraphUpdate) ClearLayout() *MindmapGraphUpdate {
	_u.mutation.ClearLayout()
	return _u
}

// SetGeneratedAt sets the "generated_at" field.
func (_u *MindmapGraphUpdate) SetGeneratedAt(v time.Time) *MindmapGraphUpdate {
	_u.mutation.SetGeneratedAt(v)
	return _u
}

// SetNillableGeneratedAt sets the "generated_at" field if the given value is not nil.
func (_u *MindmapGraphUpdate) SetNillableGeneratedAt(v *time.Time) *MindmapGraphUpdate {
	if v != nil {
		_u.SetGeneratedAt(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *MindmapGraphUpdate) SetVersion(v int) *MindmapGraphUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *MindmapGraphUpdate) SetNillableVersion(v *int) *MindmapGraphUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *MindmapGraphUpdate) AddVersion(v int) *MindmapGraphUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetSessionID sets the "session" edge to the Session entity by ID.
func (_u *MindmapGraphUpdate) SetSessionID(id uuid.UUID) *MindmapGraphUpdate {
	_u.mutation.SetSessionID(id)
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *MindmapGraphUpdate) SetSession(v *Session) *MindmapGraphUpdate {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the MindmapGraphMutation object of the builder.
func (_u *MindmapGraphUpdate) Mutation() *MindmapGraphMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *MindmapGraphUpdate) ClearSession() *MindmapGraphUpdate {
	_u.mutation.ClearSession()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MindmapGraphUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MindmapGraphUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MindmapGraphUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MindmapGraphUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MindmapGraphUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mindmapgraph.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MindmapGraphUpdate) check() error {
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MindmapGraph.session"`)
	}
	return nil
}

func (_u *MindmapGraphUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mindmapgraph.Table, mindmapgraph.Columns, sqlgraph.NewFieldSpec(mindmapgraph.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mindmapgraph.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Nodes(); ok {
		_spec.SetField(mindmapgraph.FieldNodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNodes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mindmapgraph.FieldNodes, value)
		})
	}
	if _u.mutation.NodesCleared() {
		_spec.ClearField(mindmapgraph.FieldNodes, field.TypeJSON)
	}
	if value, ok := _u.mutation.GraphEdges(); ok {
		_spec.SetField(mindmapgraph.FieldGraphEdges, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGraphEdges(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mindmapgraph.FieldGraphEdges, value)
		})
	}
	if _u.mutation.GraphEdgesCleared() {
		_spec.ClearField(mindmapgraph.FieldGraphEdges, field.TypeJSON)
	}
	if value, ok := _u.mutation.Layout(); ok {
		_spec.SetField(mindmapgraph.FieldLayout, field.TypeJSON, value)
	}
	if _u.mutation.LayoutCleared() {
		_spec.ClearField(mindmapgraph.FieldLayout, field.TypeJSON)
	}
	if value, ok := _u.mutation.GeneratedAt(); ok {
		_spec.SetField(mindmapgraph.FieldGeneratedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(mindmapgraph.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(mindmapgraph.FieldVersion, field.TypeInt, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mindmapgraph.SessionTable,
			Columns: []string{mindmapgraph.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mindmapgraph.SessionTable,
			Columns: []string{mindmapgraph.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mindmapgraph.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MindmapGraphUpdateOne is the builder for updating a single MindmapGraph entity.
type MindmapGraphUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MindmapGraphMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MindmapGraphUpdateOne) SetUpdatedAt(v time.Time) *MindmapGraphUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNodes sets the "nodes" field.
func (_u *MindmapGraphUpdateOne) SetNodes(v []map[string]interface{}) *MindmapGraphUpdateOne {
	_u.mutation.SetNodes(v)
	return _u
}

// AppendNodes appends value to the "nodes" field.
func (_u *MindmapGraphUpdateOne) AppendNodes(v []map[string]interface{}) *MindmapGraphUpdateOne {
	_u.mutation.AppendNodes(v)
	return _u
}

// ClearNodes clears the value of the "nodes" field.
func (_u *MindmapGraphUpdateOne) ClearNodes() *MindmapGraphUpdateOne {
	_u.mutation.ClearNodes()
	return _u
}

// SetGraphEdges sets the "graph_edges" field.
func (_u *MindmapGraphUpdateOne) SetGraphEdges(v []map[string]interface{}) *MindmapGraphUpdateOne {
	_u.mutation.SetGraphEdges(v)
	return _u
}

// AppendGraphEdges appends value to the "graph_edges" field.
func (_u *MindmapGraphUpdateOne) AppendGraphEdges(v []map[string]interface{}) *MindmapGraphUpdateOne {
	_u.mutation.AppendGraphEdges(v)
	return _u
}

// ClearGraphEdges clears the value of the "graph_edges" field.
func (_u *MindmapGraphUpdateOne) ClearGraphEdges() *MindmapGraphUpdateOne {
	_u.mutation.ClearGraphEdges()
	return _u
}

// SetLayout sets the "layout" field.
func (_u *MindmapGraphUpdateOne) SetLayout(v map[string]interface{}) *MindmapGraphUpdateOne {
	_u.mutation.SetLayout(v)
	return _u
}

// ClearLayout clears the value of the "layout" field.
func (_u *MindmapGraphUpdateOne) ClearLayout() *MindmapGraphUpdateOne {
	_u.mutation.ClearLayout()
	return _u
}

// SetGeneratedAt sets the "generated_at" field.
func (_u *MindmapGraphUpdateOne) SetGeneratedAt(v time.Time) *MindmapGraphUpdateOne {
	_u.mutation.SetGeneratedAt(v)
	return _u
}

// SetNillableGeneratedAt sets the "generated_at" field if the given value is not nil.
func (_u *MindmapGraphUpdateOne) SetNillableGeneratedAt(v *time.Time) *MindmapGraphUpdateOne {
	if v != nil {
		_u.SetGeneratedAt(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *MindmapGraphUpdateOne) SetVersion(v int) *MindmapGraphUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *MindmapGraphUpdateOne) SetNillableVersion(v *int) *MindmapGraphUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *MindmapGraphUpdateOne) AddVersion(v int) *MindmapGraphUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetSessionID sets the "session" edge to the Session entity by ID.
func (_u *MindmapGraphUpdateOne) SetSessionID(id uuid.UUID) *MindmapGraphUpdateOne {
	_u.mutation.SetSessionID(id)
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *MindmapGraphUpdateOne) SetSession(v *Session) *MindmapGraphUpdateOne {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the MindmapGraphMutation object of the builder.
func (_u *MindmapGraphUpdateOne) Mutation() *MindmapGraphMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *MindmapGraphUpdateOne) ClearSession() *MindmapGraphUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// Where appends a list predicates to the MindmapGraphUpdate builder.
func (_u *MindmapGraphUpdateOne) Where(ps ...predicate.MindmapGraph) *MindmapGraphUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MindmapGraphUpdateOne) Select(field string, fields ...string) *MindmapGraphUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MindmapGraph entity.
func (_u *MindmapGraphUpdateOne) Save(ctx context.Context) (*MindmapGraph, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MindmapGraphUpdateOne) SaveX(ctx context.Context) *MindmapGraph {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MindmapGraphUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MindmapGraphUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MindmapGraphUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mindmapgraph.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MindmapGraphUpdateOne) check() error {
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MindmapGraph.session"`)
	}
	return nil
}

func (_u *MindmapGraphUpdateOne) sqlSave(ctx context.Context) (_node *MindmapGraph, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mindmapgraph.Table, mindmapgraph.Columns, sqlgraph.NewFieldSpec(mindmapgraph.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MindmapGraph.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mindmapgraph.FieldID)
		for _, f := range fields {
			if !mindmapgraph.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mindmapgraph.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mindmapgraph.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Nodes(); ok {
		_spec.SetField(mindmapgraph.FieldNodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNodes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mindmapgraph.FieldNodes, value)
		})
	}
	if _u.mutation.NodesCleared() {
		_spec.ClearField(mindmapgraph.FieldNodes, field.TypeJSON)
	}
	if value, ok := _u.mutation.GraphEdges(); ok {
		_spec.SetField(mindmapgraph.FieldGraphEdges, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGraphEdges(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mindmapgraph.FieldGraphEdges, value)
		})
	}
	if _u.mutation.GraphEdgesCleared() {
		_spec.ClearField(mindmapgraph.FieldGraphEdges, field.TypeJSON)
	}
	if value, ok := _u.mutation.Layout(); ok {
		_spec.SetField(mindmapgraph.FieldLayout, field.TypeJSON, value)
	}
	if _u.mutation.LayoutCleared() {
		_spec.ClearField(mindmapgraph.FieldLayout, field.TypeJSON)
	}
	if value, ok := _u.mutation.GeneratedAt(); ok {
		_spec.SetField(mindmapgraph.FieldGeneratedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(mindmapgraph.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(mindmapgraph.FieldVersion, field.TypeInt, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mindmapgraph.SessionTable,
			Columns: []string{mindmapgraph.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mindmapgraph.SessionTable,
			Columns: []string{mindmapgraph.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MindmapGraph{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mindmapgraph.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
