// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mindhit/api/ent/mindmapgraph"
	"github.com/mindhit/api/ent/predicate"
)

// MindmapGraphDelete is the builder for deleting a MindmapGraph entity.
type MindmapGraphDelete struct {
	config
	hooks    []Hook
	mutation *MindmapGraphMutation
}

// Where appends a list predicates to the MindmapGraphDelete builder.
func (_d *MindmapGraphDelete) Where(ps ...predicate.MindmapGraph) *MindmapGraphDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MindmapGraphDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MindmapGraphDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MindmapGraphDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mindmapgraph.Table, sqlgraph.NewFieldSpec(mindmapgraph.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MindmapGraphDeleteOne is the builder for deleting a single MindmapGraph entity.
type MindmapGraphDeleteOne struct {
	_d *MindmapGraphDelete
}

// Where appends a list predicates to the MindmapGraphDelete builder.
func (_d *MindmapGraphDeleteOne) Where(ps ...predicate.MindmapGraph) *MindmapGraphDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MindmapGraphDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mindmapgraph.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MindmapGraphDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
