// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mindhit/api/ent/pagevisit"
	"github.com/mindhit/api/ent/session"
	"github.com/mindhit/api/ent/url"
)

// PageVisitCreate is the builder for creating a PageVisit entity.
type PageVisitCreate struct {
	config
	mutation *PageVisitMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PageVisitCreate) SetCreatedAt(v time.Time) *PageVisitCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PageVisitCreate) SetNillableCreatedAt(v *time.Time) *PageVisitCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PageVisitCreate) SetUpdatedAt(v time.Time) *PageVisitCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PageVisitCreate) SetNillableUpdatedAt(v *time.Time) *PageVisitCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEnteredAt sets the "entered_at" field.
func (_c *PageVisitCreate) SetEnteredAt(v time.Time) *PageVisitCreate {
	_c.mutation.SetEnteredAt(v)
	return _c
}

// SetNillableEnteredAt sets the "entered_at" field if the given value is not nil.
func (_c *PageVisitCreate) SetNillableEnteredAt(v *time.Time) *PageVisitCreate {
	if v != nil {
		_c.SetEnteredAt(*v)
	}
	return _c
}

// SetLeftAt sets the "left_at" field.
func (_c *PageVisitCreate) SetLeftAt(v time.Time) *PageVisitCreate {
	_c.mutation.SetLeftAt(v)
	return _c
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (_c *PageVisitCreate) SetNillableLeftAt(v *time.Time) *PageVisitCreate {
	if v != nil {
		_c.SetLeftAt(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *PageVisitCreate) SetDurationMs(v int) *PageVisitCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *PageVisitCreate) SetNillableDurationMs(v *int) *PageVisitCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetMaxScrollDepth sets the "max_scroll_depth" field.
func (_c *PageVisitCreate) SetMaxScrollDepth(v float64) *PageVisitCreate {
	_c.mutation.SetMaxScrollDepth(v)
	return _c
}

// SetNillableMaxScrollDepth sets the "max_scroll_depth" field if the given value is not nil.
func (_c *PageVisitCreate) SetNillableMaxScrollDepth(v *float64) *PageVisitCreate {
	if v != nil {
		_c.SetMaxScrollDepth(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PageVisitCreate) SetID(v uuid.UUID) *PageVisitCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PageVisitCreate) SetNillableID(v *uuid.UUID) *PageVisitCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSessionID sets the "session" edge to the Session entity by ID.
func (_c *PageVisitCreate) SetSessionID(id uuid.UUID) *PageVisitCreate {
	_c.mutation.SetSessionID(id)
	return _c
}

// SetSession sets the "session" edge to the Session entity.
func (_c *PageVisitCreate) SetSession(v *Session) *PageVisitCreate {
	return _c.SetSessionID(v.ID)
}

// SetURLID sets the "url" edge to the URL entity by ID.
func (_c *PageVisitCreate) SetURLID(id uuid.UUID) *PageVisitCreate {
	_c.mutation.SetURLID(id)
	return _c
}

// SetURL sets the "url" edge to the URL entity.
func (_c *PageVisitCreate) SetURL(v *URL) *PageVisitCreate {
	return _c.SetURLID(v.ID)
}

// Mutation returns the PageVisitMutation object of the builder.
func (_c *PageVisitCreate) Mutation() *PageVisitMutation {
	return _c.mutation
}

// Save creates the PageVisit in the database.
func (_c *PageVisitCreate) Save(ctx context.Context) (*PageVisit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PageVisitCreate) SaveX(ctx context.Context) *PageVisit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PageVisitCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PageVisitCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PageVisitCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pagevisit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := pagevisit.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.EnteredAt(); !ok {
		v := pagevisit.DefaultEnteredAt()
		_c.mutation.SetEnteredAt(v)
	}
	if _, ok := _c.mutation.MaxScrollDepth(); !ok {
		v := pagevisit.DefaultMaxScrollDepth
		_c.mutation.SetMaxScrollDepth(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := pagevisit.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PageVisitCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PageVisit.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PageVisit.updated_at"`)}
	}
	if _, ok := _c.mutation.EnteredAt(); !ok {
		return &ValidationError{Name: "entered_at", err: errors.New(`ent: missing required field "PageVisit.entered_at"`)}
	}
	if _, ok := _c.mutation.MaxScrollDepth(); !ok {
		return &ValidationError{Name: "max_scroll_depth", err: errors.New(`ent: missing required field "PageVisit.max_scroll_depth"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "PageVisit.session"`)}
	}
	if len(_c.mutation.URLIDs()) == 0 {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required edge "PageVisit.url"`)}
	}
	return nil
}

func (_c *PageVisitCreate) sqlSave(ctx context.Context) (*PageVisit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PageVisitCreate) createSpec() (*PageVisit, *sqlgraph.CreateSpec) {
	var (
		_node = &PageVisit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pagevisit.Table, sqlgraph.NewFieldSpec(pagevisit.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pagevisit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pagevisit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.EnteredAt(); ok {
		_spec.SetField(pagevisit.FieldEnteredAt, field.TypeTime, value)
		_node.EnteredAt = value
	}
	if value, ok := _c.mutation.LeftAt(); ok {
		_spec.SetField(pagevisit.FieldLeftAt, field.TypeTime, value)
		_node.LeftAt = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(pagevisit.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = &value
	}
	if value, ok := _c.mutation.MaxScrollDepth(); ok {
		_spec.SetField(pagevisit.FieldMaxScrollDepth, field.TypeFloat64, value)
		_node.MaxScrollDepth = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pagevisit.SessionTable,
			Columns: []string{pagevisit.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.session_page_visits = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.URLIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pagevisit.URLTable,
			Columns: []string{pagevisit.URLColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(url.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.page_visit_url = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PageVisitCreateBulk is the builder for creating many PageVisit entities in bulk.
type PageVisitCreateBulk struct {
	config
	err      error
	builders []*PageVisitCreate
}

// Save creates the PageVisit entities in the database.
func (_c *PageVisitCreateBulk) Save(ctx context.Context) ([]*PageVisit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PageVisit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PageVisitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PageVisitCreateBulk) SaveX(ctx context.Context) []*PageVisit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PageVisitCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PageVisitCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
