// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mindhit/api/ent/plan"
	"github.com/mindhit/api/ent/predicate"
	"github.com/mindhit/api/ent/subscription"
)

// PlanUpdate is the builder for updating Plan entities.
type PlanUpdate struct {
	config
	hooks    []Hook
	mutation *PlanMutation
}

// Where appends a list predicates to the PlanUpdate builder.
func (_u *PlanUpdate) Where(ps ...predicate.Plan) *PlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PlanUpdate) SetName(v string) *PlanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableName(v *string) *PlanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPriceCents sets the "price_cents" field.
func (_u *PlanUpdate) SetPriceCents(v int) *PlanUpdate {
	_u.mutation.ResetPriceCents()
	_u.mutation.SetPriceCents(v)
	return _u
}

// SetNillablePriceCents sets the "price_cents" field if the given value is not nil.
func (_u *PlanUpdate) SetNillablePriceCents(v *int) *PlanUpdate {
	if v != nil {
		_u.SetPriceCents(*v)
	}
	return _u
}

// AddPriceCents adds value to the "price_cents" field.
func (_u *PlanUpdate) AddPriceCents(v int) *PlanUpdate {
	_u.mutation.AddPriceCents(v)
	return _u
}

// SetBillingPeriod sets the "billing_period" field.
func (_u *PlanUpdate) SetBillingPeriod(v string) *PlanUpdate {
	_u.mutation.SetBillingPeriod(v)
	return _u
}

// SetNillableBillingPeriod sets the "billing_period" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableBillingPeriod(v *string) *PlanUpdate {
	if v != nil {
		_u.SetBillingPeriod(*v)
	}
	return _u
}

// SetTokenLimit sets the "token_limit" field.
func (_u *PlanUpdate) SetTokenLimit(v int) *PlanUpdate {
	_u.mutation.ResetTokenLimit()
	_u.mutation.SetTokenLimit(v)
	return _u
}

// SetNillableTokenLimit sets the "token_limit" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableTokenLimit(v *int) *PlanUpdate {
	if v != nil {
		_u.SetTokenLimit(*v)
	}
	return _u
}

// AddTokenLimit adds value to the "token_limit" field.
func (_u *PlanUpdate) AddTokenLimit(v int) *PlanUpdate {
	_u.mutation.AddTokenLimit(v)
	return _u
}

// ClearTokenLimit clears the value of the "token_limit" field.
func (_u *PlanUpdate) ClearTokenLimit() *PlanUpdate {
	_u.mutation.ClearTokenLimit()
	return _u
}

// SetSessionRetentionDays sets the "session_retention_days" field.
func (_u *PlanUpdate) SetSessionRetentionDays(v int) *PlanUpdate {
	_u.mutation.ResetSessionRetentionDays()
	_u.mutation.SetSessionRetentionDays(v)
	return _u
}

// SetNillableSessionRetentionDays sets the "session_retention_days" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableSessionRetentionDays(v *int) *PlanUpdate {
	if v != nil {
		_u.SetSessionRetentionDays(*v)
	}
	return _u
}

// AddSessionRetentionDays adds value to the "session_retention_days" field.
func (_u *PlanUpdate) AddSessionRetentionDays(v int) *PlanUpdate {
	_u.mutation.AddSessionRetentionDays(v)
	return _u
}

// ClearSessionRetentionDays clears the value of the "session_retention_days" field.
func (_u *PlanUpdate) ClearSessionRetentionDays() *PlanUpdate {
	_u.mutation.ClearSessionRetentionDays()
	return _u
}

// SetMaxConcurrentSessions sets the "max_concurrent_sessions" field.
func (_u *PlanUpdate) SetMaxConcurrentSessions(v int) *PlanUpdate {
	_u.mutation.ResetMaxConcurrentSessions()
	_u.mutation.SetMaxConcurrentSessions(v)
	return _u
}

// SetNillableMaxConcurrentSessions sets the "max_concurrent_sessions" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableMaxConcurrentSessions(v *int) *PlanUpdate {
	if v != nil {
		_u.SetMaxConcurrentSessions(*v)
	}
	return _u
}

// AddMaxConcurrentSessions adds value to the "max_concurrent_sessions" field.
func (_u *PlanUpdate) AddMaxConcurrentSessions(v int) *PlanUpdate {
	_u.mutation.AddMaxConcurrentSessions(v)
	return _u
}

// ClearMaxConcurrentSessions clears the value of the "max_concurrent_sessions" field.
func (_u *PlanUpdate) ClearMaxConcurrentSessions() *PlanUpdate {
	_u.mutation.ClearMaxConcurrentSessions()
	return _u
}

// SetFeatures sets the "features" field.
func (_u *PlanUpdate) SetFeatures(v map[string]bool) *PlanUpdate {
	_u.mutation.SetFeatures(v)
	return _u
}

// AddSubscriptionIDs adds the "subscriptions" edge to the Subscription entity by IDs.
func (_u *PlanUpdate) AddSubscriptionIDs(ids ...uuid.UUID) *PlanUpdate {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the Subscription entity.
func (_u *PlanUpdate) AddSubscriptions(v ...*Subscription) *PlanUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (_u *PlanUpdate) Mutation() *PlanMutation {
	return _u.mutation
}

// ClearSubscriptions clears all "subscriptions" edges to the Subscription entity.
func (_u *PlanUpdate) ClearSubscriptions() *PlanUpdate {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to Subscription entities by IDs.
func (_u *PlanUpdate) RemoveSubscriptionIDs(ids ...uuid.UUID) *PlanUpdate {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to Subscription entities.
func (_u *PlanUpdate) RemoveSubscriptions(v ...*Subscription) *PlanUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlanUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlanUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := plan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plan.name": %w`, err)}
		}
	}
	return nil
}

func (_u *PlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plan.Table, plan.Columns, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(plan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceCents(); ok {
		_spec.SetField(plan.FieldPriceCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriceCents(); ok {
		_spec.AddField(plan.FieldPriceCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BillingPeriod(); ok {
		_spec.SetField(plan.FieldBillingPeriod, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenLimit(); ok {
		_spec.SetField(plan.FieldTokenLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenLimit(); ok {
		_spec.AddField(plan.FieldTokenLimit, field.TypeInt, value)
	}
	if _u.mutation.TokenLimitCleared() {
		_spec.ClearField(plan.FieldTokenLimit, field.TypeInt)
	}
	if value, ok := _u.mutation.SessionRetentionDays(); ok {
		_spec.SetField(plan.FieldSessionRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSessionRetentionDays(); ok {
		_spec.AddField(plan.FieldSessionRetentionDays, field.TypeInt, value)
	}
	if _u.mutation.SessionRetentionDaysCleared() {
		_spec.ClearField(plan.FieldSessionRetentionDays, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxConcurrentSessions(); ok {
		_spec.SetField(plan.FieldMaxConcurrentSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxConcurrentSessions(); ok {
		_spec.AddField(plan.FieldMaxConcurrentSessions, field.TypeInt, value)
	}
	if _u.mutation.MaxConcurrentSessionsCleared() {
		_spec.ClearField(plan.FieldMaxConcurrentSessions, field.TypeInt)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(plan.FieldFeatures, field.TypeJSON, value)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.SubscriptionsTable,
			Columns: []string{plan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.SubscriptionsTable,
			Columns: []string{plan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.SubscriptionsTable,
			Columns: []string{plan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlanUpdateOne is the builder for updating a single Plan entity.
type PlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlanMutation
}

// SetName sets the "name" field.
func (_u *PlanUpdateOne) SetName(v string) *PlanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableName(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPriceCents sets the "price_cents" field.
func (_u *PlanUpdateOne) SetPriceCents(v int) *PlanUpdateOne {
	_u.mutation.ResetPriceCents()
	_u.mutation.SetPriceCents(v)
	return _u
}

// SetNillablePriceCents sets the "price_cents" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillablePriceCents(v *int) *PlanUpdateOne {
	if v != nil {
		_u.SetPriceCents(*v)
	}
	return _u
}

// AddPriceCents adds value to the "price_cents" field.
func (_u *PlanUpdateOne) AddPriceCents(v int) *PlanUpdateOne {
	_u.mutation.AddPriceCents(v)
	return _u
}

// SetBillingPeriod sets the "billing_period" field.
func (_u *PlanUpdateOne) SetBillingPeriod(v string) *PlanUpdateOne {
	_u.mutation.SetBillingPeriod(v)
	return _u
}

// SetNillableBillingPeriod sets the "billing_period" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableBillingPeriod(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetBillingPeriod(*v)
	}
	return _u
}

// SetTokenLimit sets the "token_limit" field.
func (_u *PlanUpdateOne) SetTokenLimit(v int) *PlanUpdateOne {
	_u.mutation.ResetTokenLimit()
	_u.mutation.SetTokenLimit(v)
	return _u
}

// SetNillableTokenLimit sets the "token_limit" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableTokenLimit(v *int) *PlanUpdateOne {
	if v != nil {
		_u.SetTokenLimit(*v)
	}
	return _u
}

// AddTokenLimit adds value to the "token_limit" field.
func (_u *PlanUpdateOne) AddTokenLimit(v int) *PlanUpdateOne {
	_u.mutation.AddTokenLimit(v)
	return _u
}

// ClearTokenLimit clears the value of the "token_limit" field.
func (_u *PlanUpdateOne) ClearTokenLimit() *PlanUpdateOne {
	_u.mutation.ClearTokenLimit()
	return _u
}

// SetSessionRetentionDays sets the "session_retention_days" field.
func (_u *PlanUpdateOne) SetSessionRetentionDays(v int) *PlanUpdateOne {
	_u.mutation.ResetSessionRetentionDays()
	_u.mutation.SetSessionRetentionDays(v)
	return _u
}

// SetNillableSessionRetentionDays sets the "session_retention_days" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableSessionRetentionDays(v *int) *PlanUpdateOne {
	if v != nil {
		_u.SetSessionRetentionDays(*v)
	}
	return _u
}

// AddSessionRetentionDays adds value to the "session_retention_days" field.
func (_u *PlanUpdateOne) AddSessionRetentionDays(v int) *PlanUpdateOne {
	_u.mutation.AddSessionRetentionDays(v)
	return _u
}

// ClearSessionRetentionDays clears the value of the "session_retention_days" field.
func (_u *PlanUpdateOne) ClearSessionRetentionDays() *PlanUpdateOne {
	_u.mutation.ClearSessionRetentionDays()
	return _u
}

// SetMaxConcurrentSessions sets the "max_concurrent_sessions" field.
func (_u *PlanUpdateOne) SetMaxConcurrentSessions(v int) *PlanUpdateOne {
	_u.mutation.ResetMaxConcurrentSessions()
	_u.mutation.SetMaxConcurrentSessions(v)
	return _u
}

// SetNillableMaxConcurrentSessions sets the "max_concurrent_sessions" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableMaxConcurrentSessions(v *int) *PlanUpdateOne {
	if v != nil {
		_u.SetMaxConcurrentSessions(*v)
	}
	return _u
}

// AddMaxConcurrentSessions adds value to the "max_concurrent_sessions" field.
func (_u *PlanUpdateOne) AddMaxConcurrentSessions(v int) *PlanUpdateOne {
	_u.mutation.AddMaxConcurrentSessions(v)
	return _u
}

// ClearMaxConcurrentSessions clears the value of the "max_concurrent_sessions" field.
func (_u *PlanUpdateOne) ClearMaxConcurrentSessions() *PlanUpdateOne {
	_u.mutation.ClearMaxConcurrentSessions()
	return _u
}

// SetFeatures sets the "features" field.
func (_u *PlanUpdateOne) SetFeatures(v map[string]bool) *PlanUpdateOne {
	_u.mutation.SetFeatures(v)
	return _u
}

// AddSubscriptionIDs adds the "subscriptions" edge to the Subscription entity by IDs.
func (_u *PlanUpdateOne) AddSubscriptionIDs(ids ...uuid.UUID) *PlanUpdateOne {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the Subscription entity.
func (_u *PlanUpdateOne) AddSubscriptions(v ...*Subscription) *PlanUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (_u *PlanUpdateOne) Mutation() *PlanMutation {
	return _u.mutation
}

// ClearSubscriptions clears all "subscriptions" edges to the Subscription entity.
func (_u *PlanUpdateOne) ClearSubscriptions() *PlanUpdateOne {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to Subscription entities by IDs.
func (_u *PlanUpdateOne) RemoveSubscriptionIDs(ids ...uuid.UUID) *PlanUpdateOne {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to Subscription entities.
func (_u *PlanUpdateOne) RemoveSubscriptions(v ...*Subscription) *PlanUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// Where appends a list predicates to the PlanUpdate builder.
func (_u *PlanUpdateOne) Where(ps ...predicate.Plan) *PlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlanUpdateOne) Select(field string, fields ...string) *PlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Plan entity.
func (_u *PlanUpdateOne) Save(ctx context.Context) (*Plan, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlanUpdateOne) SaveX(ctx context.Context) *Plan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlanUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := plan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plan.name": %w`, err)}
		}
	}
	return nil
}

func (_u *PlanUpdateOne) sqlSave(ctx context.Context) (_node *Plan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plan.Table, plan.Columns, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Plan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plan.FieldID)
		for _, f := range fields {
			if !plan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != plan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(plan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceCents(); ok {
		_spec.SetField(plan.FieldPriceCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriceCents(); ok {
		_spec.AddField(plan.FieldPriceCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BillingPeriod(); ok {
		_spec.SetField(plan.FieldBillingPeriod, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenLimit(); ok {
		_spec.SetField(plan.FieldTokenLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenLimit(); ok {
		_spec.AddField(plan.FieldTokenLimit, field.TypeInt, value)
	}
	if _u.mutation.TokenLimitCleared() {
		_spec.ClearField(plan.FieldTokenLimit, field.TypeInt)
	}
	if value, ok := _u.mutation.SessionRetentionDays(); ok {
		_spec.SetField(plan.FieldSessionRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSessionRetentionDays(); ok {
		_spec.AddField(plan.FieldSessionRetentionDays, field.TypeInt, value)
	}
	if _u.mutation.SessionRetentionDaysCleared() {
		_spec.ClearField(plan.FieldSessionRetentionDays, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxConcurrentSessions(); ok {
		_spec.SetField(plan.FieldMaxConcurrentSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxConcurrentSessions(); ok {
		_spec.AddField(plan.FieldMaxConcurrentSessions, field.TypeInt, value)
	}
	if _u.mutation.MaxConcurrentSessionsCleared() {
		_spec.ClearField(plan.FieldMaxConcurrentSessions, field.TypeInt)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(plan.FieldFeatures, field.TypeJSON, value)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.SubscriptionsTable,
			Columns: []string{plan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.SubscriptionsTable,
			Columns: []string{plan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.SubscriptionsTable,
			Columns: []string{plan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Plan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
