// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mindhit/api/ent/plan"
)

// Plan is the model entity for the Plan schema.
type Plan struct {
	config `json:"-"`
	// ID of the ent.
	// Plan identifier: 'free', 'pro', 'enterprise'
	ID string `json:"id,omitempty"`
	// Display name of the plan
	Name string `json:"name,omitempty"`
	// Monthly price in cents (0 for free, null for custom)
	PriceCents int `json:"price_cents,omitempty"`
	// Billing period: 'monthly' or 'yearly'
	BillingPeriod string `json:"billing_period,omitempty"`
	// Monthly token limit (null = unlimited)
	TokenLimit *int `json:"token_limit,omitempty"`
	// Days to retain sessions (null = unlimited)
	SessionRetentionDays *int `json:"session_retention_days,omitempty"`
	// Max concurrent sessions (null = unlimited)
	MaxConcurrentSessions *int `json:"max_concurrent_sessions,omitempty"`
	// Feature flags for this plan
	Features map[string]bool `json:"features,omitempty"`
	// Plan creation time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlanQuery when eager-loading is set.
	Edges        PlanEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PlanEdges holds the relations/edges for other nodes in the graph.
type PlanEdges struct {
	// Subscriptions holds the value of the subscriptions edge.
	Subscriptions []*Subscription `json:"subscriptions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SubscriptionsOrErr returns the Subscriptions value or an error if the edge
// was not loaded in eager-loading.
func (e PlanEdges) SubscriptionsOrErr() ([]*Subscription, error) {
	if e.loadedTypes[0] {
		return e.Subscriptions, nil
	}
	return nil, &NotLoadedError{edge: "subscriptions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Plan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case plan.FieldFeatures:
			values[i] = new([]byte)
		case plan.FieldPriceCents, plan.FieldTokenLimit, plan.FieldSessionRetentionDays, plan.FieldMaxConcurrentSessions:
			values[i] = new(sql.NullInt64)
		case plan.FieldID, plan.FieldName, plan.FieldBillingPeriod:
			values[i] = new(sql.NullString)
		case plan.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Plan fields.
func (_m *Plan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case plan.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case plan.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case plan.FieldPriceCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_cents", values[i])
			} else if value.Valid {
				_m.PriceCents = int(value.Int64)
			}
		case plan.FieldBillingPeriod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_period", values[i])
			} else if value.Valid {
				_m.BillingPeriod = value.String
			}
		case plan.FieldTokenLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field token_limit", values[i])
			} else if value.Valid {
				_m.TokenLimit = new(int)
				*_m.TokenLimit = int(value.Int64)
			}
		case plan.FieldSessionRetentionDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field session_retention_days", values[i])
			} else if value.Valid {
				_m.SessionRetentionDays = new(int)
				*_m.SessionRetentionDays = int(value.Int64)
			}
		case plan.FieldMaxConcurrentSessions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_concurrent_sessions", values[i])
			} else if value.Valid {
				_m.MaxConcurrentSessions = new(int)
				*_m.MaxConcurrentSessions = int(value.Int64)
			}
		case plan.FieldFeatures:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field features", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Features); err != nil {
					return fmt.Errorf("unmarshal field features: %w", err)
				}
			}
		case plan.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Plan.
// This includes values selected through modifiers, order, etc.
func (_m *Plan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySubscriptions queries the "subscriptions" edge of the Plan entity.
func (_m *Plan) QuerySubscriptions() *SubscriptionQuery {
	return NewPlanClient(_m.config).QuerySubscriptions(_m)
}

// Update returns a builder for updating this Plan.
// Note that you need to call Plan.Unwrap() before calling this method if this Plan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Plan) Update() *PlanUpdateOne {
	return NewPlanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Plan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Plan) Unwrap() *Plan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Plan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Plan) String() string {
	var builder strings.Builder
	builder.WriteString("Plan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("price_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceCents))
	builder.WriteString(", ")
	builder.WriteString("billing_period=")
	builder.WriteString(_m.BillingPeriod)
	builder.WriteString(", ")
	if v := _m.TokenLimit; v != nil {
		builder.WriteString("token_limit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SessionRetentionDays; v != nil {
		builder.WriteString("session_retention_days=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MaxConcurrentSessions; v != nil {
		builder.WriteString("max_concurrent_sessions=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("features=")
	builder.WriteString(fmt.Sprintf("%v", _m.Features))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Plans is a parsable slice of Plan.
type Plans []*Plan
