// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/mindhit/api/ent/rawevent"
	"github.com/mindhit/api/ent/session"
)

// RawEvent is the model entity for the RawEvent schema.
type RawEvent struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key
	ID uuid.UUID `json:"id,omitempty"`
	// Record creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Record last update timestamp
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Event type (page_visit, highlight, scroll, etc.)
	EventType string `json:"event_type,omitempty"`
	// Client-side event timestamp
	Timestamp time.Time `json:"timestamp,omitempty"`
	// Raw JSON event payload
	Payload string `json:"payload,omitempty"`
	// Whether event has been processed
	Processed bool `json:"processed,omitempty"`
	// When event was processed
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RawEventQuery when eager-loading is set.
	Edges              RawEventEdges `json:"edges"`
	session_raw_events *uuid.UUID
	selectValues       sql.SelectValues
}

// RawEventEdges holds the relations/edges for other nodes in the graph.
type RawEventEdges struct {
	// Session holds the value of the session edge.
	Session *Session `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RawEventEdges) SessionOrErr() (*Session, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: session.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RawEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rawevent.FieldProcessed:
			values[i] = new(sql.NullBool)
		case rawevent.FieldEventType, rawevent.FieldPayload:
			values[i] = new(sql.NullString)
		case rawevent.FieldCreatedAt, rawevent.FieldUpdatedAt, rawevent.FieldTimestamp, rawevent.FieldProcessedAt:
			values[i] = new(sql.NullTime)
		case rawevent.FieldID:
			values[i] = new(uuid.UUID)
		case rawevent.ForeignKeys[0]: // session_raw_events
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RawEvent fields.
func (_m *RawEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rawevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case rawevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rawevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case rawevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case rawevent.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		case rawevent.FieldPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value.Valid {
				_m.Payload = value.String
			}
		case rawevent.FieldProcessed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field processed", values[i])
			} else if value.Valid {
				_m.Processed = value.Bool
			}
		case rawevent.FieldProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processed_at", values[i])
			} else if value.Valid {
				_m.ProcessedAt = new(time.Time)
				*_m.ProcessedAt = value.Time
			}
		case rawevent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field session_raw_events", values[i])
			} else if value.Valid {
				_m.session_raw_events = new(uuid.UUID)
				*_m.session_raw_events = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RawEvent.
// This includes values selected through modifiers, order, etc.
func (_m *RawEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the RawEvent entity.
func (_m *RawEvent) QuerySession() *SessionQuery {
	return NewRawEventClient(_m.config).QuerySession(_m)
}

// Update returns a builder for updating this RawEvent.
// Note that you need to call RawEvent.Unwrap() before calling this method if this RawEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RawEvent) Update() *RawEventUpdateOne {
	return NewRawEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RawEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RawEvent) Unwrap() *RawEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RawEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RawEvent) String() string {
	var builder strings.Builder
	builder.WriteString("RawEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(_m.Payload)
	builder.WriteString(", ")
	builder.WriteString("processed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Processed))
	builder.WriteString(", ")
	if v := _m.ProcessedAt; v != nil {
		builder.WriteString("processed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// RawEvents is a parsable slice of RawEvent.
type RawEvents []*RawEvent
