// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mindhit/api/ent/ailog"
	"github.com/mindhit/api/ent/highlight"
	"github.com/mindhit/api/ent/mindmapgraph"
	"github.com/mindhit/api/ent/pagevisit"
	"github.com/mindhit/api/ent/predicate"
	"github.com/mindhit/api/ent/rawevent"
	"github.com/mindhit/api/ent/session"
	"github.com/mindhit/api/ent/tokenusage"
	"github.com/mindhit/api/ent/user"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SessionUpdate) SetUpdatedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SessionUpdate) SetStatus(v session.Status) *SessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableStatus(v *session.Status) *SessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SessionUpdate) SetDeletedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableDeletedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SessionUpdate) ClearDeletedAt() *SessionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTitle sets the "title" field.
func (_u *SessionUpdate) SetTitle(v string) *SessionUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableTitle(v *string) *SessionUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *SessionUpdate) ClearTitle() *SessionUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SessionUpdate) SetDescription(v string) *SessionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableDescription(v *string) *SessionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SessionUpdate) ClearDescription() *SessionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetSessionStatus sets the "session_status" field.
func (_u *SessionUpdate) SetSessionStatus(v session.SessionStatus) *SessionUpdate {
	_u.mutation.SetSessionStatus(v)
	return _u
}

// SetNillableSessionStatus sets the "session_status" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableSessionStatus(v *session.SessionStatus) *SessionUpdate {
	if v != nil {
		_u.SetSessionStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SessionUpdate) SetStartedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableStartedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *SessionUpdate) SetEndedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableEndedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *SessionUpdate) ClearEndedAt() *SessionUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *SessionUpdate) SetUserID(id uuid.UUID) *SessionUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SessionUpdate) SetUser(v *User) *SessionUpdate {
	return _u.SetUserID(v.ID)
}

// AddPageVisitIDs adds the "page_visits" edge to the PageVisit entity by IDs.
func (_u *SessionUpdate) AddPageVisitIDs(ids ...uuid.UUID) *SessionUpdate {
	_u.mutation.AddPageVisitIDs(ids...)
	return _u
}

// AddPageVisits adds the "page_visits" edges to the PageVisit entity.
func (_u *SessionUpdate) AddPageVisits(v ...*PageVisit) *SessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPageVisitIDs(ids...)
}

// AddHighlightIDs adds the "highlights" edge to the Highlight entity by IDs.
func (_u *SessionUpdate) AddHighlightIDs(ids ...uuid.UUID) *SessionUpdate {
	_u.mutation.AddHighlightIDs(ids...)
	return _u
}

// AddHighlights adds the "highlights" edges to the Highlight entity.
func (_u *SessionUpdate) AddHighlights(v ...*Highlight) *SessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHighlightIDs(ids...)
}

// AddRawEventIDs adds the "raw_events" edge to the RawEvent entity by IDs.
func (_u *SessionUpdate) AddRawEventIDs(ids ...uuid.UUID) *SessionUpdate {
	_u.mutation.AddRawEventIDs(ids...)
	return _u
}

// AddRawEvents adds the "raw_events" edges to the RawEvent entity.
func (_u *SessionUpdate) AddRawEvents(v ...*RawEvent) *SessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRawEventIDs(ids...)
}

// SetMindmapID sets the "mindmap" edge to the MindmapGraph entity by ID.
func (_u *SessionUpdate) SetMindmapID(id uuid.UUID) *SessionUpdate {
	_u.mutation.SetMindmapID(id)
	return _u
}

// SetNillableMindmapID sets the "mindmap" edge to the MindmapGraph entity by ID if the given value is not nil.
func (_u *SessionUpdate) SetNillableMindmapID(id *uuid.UUID) *SessionUpdate {
	if id != nil {
		_u = _u.SetMindmapID(*id)
	}
	return _u
}

// SetMindmap sets the "mindmap" edge to the MindmapGraph entity.
func (_u *SessionUpdate) SetMindmap(v *MindmapGraph) *SessionUpdate {
	return _u.SetMindmapID(v.ID)
}

// AddTokenUsageIDs adds the "token_usage" edge to the TokenUsage entity by IDs.
func (_u *SessionUpdate) AddTokenUsageIDs(ids ...uuid.UUID) *SessionUpdate {
	_u.mutation.AddTokenUsageIDs(ids...)
	return _u
}

// AddTokenUsage adds the "token_usage" edges to the TokenUsage entity.
func (_u *SessionUpdate) AddTokenUsage(v ...*TokenUsage) *SessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTokenUsageIDs(ids...)
}

// AddAiLogIDs adds the "ai_logs" edge to the AILog entity by IDs.
func (_u *SessionUpdate) AddAiLogIDs(ids ...uuid.UUID) *SessionUpdate {
	_u.mutation.AddAiLogIDs(ids...)
	return _u
}

// AddAiLogs adds the "ai_logs" edges to the AILog entity.
func (_u *SessionUpdate) AddAiLogs(v ...*AILog) *SessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAiLogIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdate) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SessionUpdate) ClearUser() *SessionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearPageVisits clears all "page_visits" edges to the PageVisit entity.
func (_u *SessionUpdate) ClearPageVisits() *SessionUpdate {
	_u.mutation.ClearPageVisits()
	return _u
}

// RemovePageVisitIDs removes the "page_visits" edge to PageVisit entities by IDs.
func (_u *SessionUpdate) RemovePageVisitIDs(ids ...uuid.UUID) *SessionUpdate {
	_u.mutation.RemovePageVisitIDs(ids...)
	return _u
}

// RemovePageVisits removes "page_visits" edges to PageVisit entities.
func (_u *SessionUpdate) RemovePageVisits(v ...*PageVisit) *SessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePageVisitIDs(ids...)
}

// ClearHighlights clears all "highlights" edges to the Highlight entity.
func (_u *SessionUpdate) ClearHighlights() *SessionUpdate {
	_u.mutation.ClearHighlights()
	return _u
}

// RemoveHighlightIDs removes the "highlights" edge to Highlight entities by IDs.
func (_u *SessionUpdate) RemoveHighlightIDs(ids ...uuid.UUID) *SessionUpdate {
	_u.mutation.RemoveHighlightIDs(ids...)
	return _u
}

// RemoveHighlights removes "highlights" edges to Highlight entities.
func (_u *SessionUpdate) RemoveHighlights(v ...*Highlight) *SessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHighlightIDs(ids...)
}

// ClearRawEvents clears all "raw_events" edges to the RawEvent entity.
func (_u *SessionUpdate) ClearRawEvents() *SessionUpdate {
	_u.mutation.ClearRawEvents()
	return _u
}

// RemoveRawEventIDs removes the "raw_events" edge to RawEvent entities by IDs.
func (_u *SessionUpdate) RemoveRawEventIDs(ids ...uuid.UUID) *SessionUpdate {
	_u.mutation.RemoveRawEventIDs(ids...)
	return _u
}

// RemoveRawEvents removes "raw_events" edges to RawEvent entities.
func (_u *SessionUpdate) RemoveRawEvents(v ...*RawEvent) *SessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRawEventIDs(ids...)
}

// ClearMindmap clears the "mindmap" edge to the MindmapGraph entity.
func (_u *SessionUpdate) ClearMindmap() *SessionUpdate {
	_u.mutation.ClearMindmap()
	return _u
}

// ClearTokenUsage clears all "token_usage" edges to the TokenUsage entity.
func (_u *SessionUpdate) ClearTokenUsage() *SessionUpdate {
	_u.mutation.ClearTokenUsage()
	return _u
}

// RemoveTokenUsageIDs removes the "token_usage" edge to TokenUsage entities by IDs.
func (_u *SessionUpdate) RemoveTokenUsageIDs(ids ...uuid.UUID) *SessionUpdate {
	_u.mutation.RemoveTokenUsageIDs(ids...)
	return _u
}

// RemoveTokenUsage removes "token_usage" edges to TokenUsage entities.
func (_u *SessionUpdate) RemoveTokenUsage(v ...*TokenUsage) *SessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTokenUsageIDs(ids...)
}

// ClearAiLogs clears all "ai_logs" edges to the AILog entity.
func (_u *SessionUpdate) ClearAiLogs() *SessionUpdate {
	_u.mutation.ClearAiLogs()
	return _u
}

// RemoveAiLogIDs removes the "ai_logs" edge to AILog entities by IDs.
func (_u *SessionUpdate) RemoveAiLogIDs(ids ...uuid.UUID) *SessionUpdate {
	_u.mutation.RemoveAiLogIDs(ids...)
	return _u
}

// RemoveAiLogs removes "ai_logs" edges to AILog entities.
func (_u *SessionUpdate) RemoveAiLogs(v ...*AILog) *SessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAiLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := session.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := session.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Session.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionStatus(); ok {
		if err := session.SessionStatusValidator(v); err != nil {
			return &ValidationError{Name: "session_status", err: fmt.Errorf(`ent: validator failed for field "Session.session_status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Session.user"`)
	}
	return nil
}

func (_u *SessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(session.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(session.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(session.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(session.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(session.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(session.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(session.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(session.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SessionStatus(); ok {
		_spec.SetField(session.FieldSessionStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(session.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(session.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(session.FieldEndedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.UserTable,
			Columns: []string{session.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.UserTable,
			Columns: []string{session.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PageVisitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PageVisitsTable,
			Columns: []string{session.PageVisitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pagevisit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPageVisitsIDs(); len(nodes) > 0 && !_u.mutation.PageVisitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PageVisitsTable,
			Columns: []string{session.PageVisitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pagevisit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PageVisitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PageVisitsTable,
			Columns: []string{session.PageVisitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pagevisit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HighlightsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.HighlightsTable,
			Columns: []string{session.HighlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(highlight.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHighlightsIDs(); len(nodes) > 0 && !_u.mutation.HighlightsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.HighlightsTable,
			Columns: []string{session.HighlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(highlight.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HighlightsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.HighlightsTable,
			Columns: []string{session.HighlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(highlight.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RawEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RawEventsTable,
			Columns: []string{session.RawEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rawevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRawEventsIDs(); len(nodes) > 0 && !_u.mutation.RawEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RawEventsTable,
			Columns: []string{session.RawEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rawevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RawEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RawEventsTable,
			Columns: []string{session.RawEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rawevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MindmapCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.MindmapTable,
			Columns: []string{session.MindmapColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mindmapgraph.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MindmapIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.MindmapTable,
			Columns: []string{session.MindmapColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mindmapgraph.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TokenUsageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.TokenUsageTable,
			Columns: []string{session.TokenUsageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenusage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTokenUsageIDs(); len(nodes) > 0 && !_u.mutation.TokenUsageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.TokenUsageTable,
			Columns: []string{session.TokenUsageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TokenUsageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.TokenUsageTable,
			Columns: []string{session.TokenUsageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AiLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.AiLogsTable,
			Columns: []string{session.AiLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ailog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAiLogsIDs(); len(nodes) > 0 && !_u.mutation.AiLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.AiLogsTable,
			Columns: []string{session.AiLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ailog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AiLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.AiLogsTable,
			Columns: []string{session.AiLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ailog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SessionUpdateOne) SetUpdatedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SessionUpdateOne) SetStatus(v session.Status) *SessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableStatus(v *session.Status) *SessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SessionUpdateOne) SetDeletedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableDeletedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SessionUpdateOne) ClearDeletedAt() *SessionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTitle sets the "title" field.
func (_u *SessionUpdateOne) SetTitle(v string) *SessionUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableTitle(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *SessionUpdateOne) ClearTitle() *SessionUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SessionUpdateOne) SetDescription(v string) *SessionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableDescription(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SessionUpdateOne) ClearDescription() *SessionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetSessionStatus sets the "session_status" field.
func (_u *SessionUpdateOne) SetSessionStatus(v session.SessionStatus) *SessionUpdateOne {
	_u.mutation.SetSessionStatus(v)
	return _u
}

// SetNillableSessionStatus sets the "session_status" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableSessionStatus(v *session.SessionStatus) *SessionUpdateOne {
	if v != nil {
		_u.SetSessionStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SessionUpdateOne) SetStartedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableStartedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *SessionUpdateOne) SetEndedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableEndedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *SessionUpdateOne) ClearEndedAt() *SessionUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *SessionUpdateOne) SetUserID(id uuid.UUID) *SessionUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SessionUpdateOne) SetUser(v *User) *SessionUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddPageVisitIDs adds the "page_visits" edge to the PageVisit entity by IDs.
func (_u *SessionUpdateOne) AddPageVisitIDs(ids ...uuid.UUID) *SessionUpdateOne {
	_u.mutation.AddPageVisitIDs(ids...)
	return _u
}

// AddPageVisits adds the "page_visits" edges to the PageVisit entity.
func (_u *SessionUpdateOne) AddPageVisits(v ...*PageVisit) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPageVisitIDs(ids...)
}

// AddHighlightIDs adds the "highlights" edge to the Highlight entity by IDs.
func (_u *SessionUpdateOne) AddHighlightIDs(ids ...uuid.UUID) *SessionUpdateOne {
	_u.mutation.AddHighlightIDs(ids...)
	return _u
}

// AddHighlights adds the "highlights" edges to the Highlight entity.
func (_u *SessionUpdateOne) AddHighlights(v ...*Highlight) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHighlightIDs(ids...)
}

// AddRawEventIDs adds the "raw_events" edge to the RawEvent entity by IDs.
func (_u *SessionUpdateOne) AddRawEventIDs(ids ...uuid.UUID) *SessionUpdateOne {
	_u.mutation.AddRawEventIDs(ids...)
	return _u
}

// AddRawEvents adds the "raw_events" edges to the RawEvent entity.
func (_u *SessionUpdateOne) AddRawEvents(v ...*RawEvent) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRawEventIDs(ids...)
}

// SetMindmapID sets the "mindmap" edge to the MindmapGraph entity by ID.
func (_u *SessionUpdateOne) SetMindmapID(id uuid.UUID) *SessionUpdateOne {
	_u.mutation.SetMindmapID(id)
	return _u
}

// SetNillableMindmapID sets the "mindmap" edge to the MindmapGraph entity by ID if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableMindmapID(id *uuid.UUID) *SessionUpdateOne {
	if id != nil {
		_u = _u.SetMindmapID(*id)
	}
	return _u
}

// SetMindmap sets the "mindmap" edge to the MindmapGraph entity.
func (_u *SessionUpdateOne) SetMindmap(v *MindmapGraph) *SessionUpdateOne {
	return _u.SetMindmapID(v.ID)
}

// AddTokenUsageIDs adds the "token_usage" edge to the TokenUsage entity by IDs.
func (_u *SessionUpdateOne) AddTokenUsageIDs(ids ...uuid.UUID) *SessionUpdateOne {
	_u.mutation.AddTokenUsageIDs(ids...)
	return _u
}

// AddTokenUsage adds the "token_usage" edges to the TokenUsage entity.
func (_u *SessionUpdateOne) AddTokenUsage(v ...*TokenUsage) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTokenUsageIDs(ids...)
}

// AddAiLogIDs adds the "ai_logs" edge to the AILog entity by IDs.
func (_u *SessionUpdateOne) AddAiLogIDs(ids ...uuid.UUID) *SessionUpdateOne {
	_u.mutation.AddAiLogIDs(ids...)
	return _u
}

// AddAiLogs adds the "ai_logs" edges to the AILog entity.
func (_u *SessionUpdateOne) AddAiLogs(v ...*AILog) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAiLogIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdateOne) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SessionUpdateOne) ClearUser() *SessionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearPageVisits clears all "page_visits" edges to the PageVisit entity.
func (_u *SessionUpdateOne) ClearPageVisits() *SessionUpdateOne {
	_u.mutation.ClearPageVisits()
	return _u
}

// RemovePageVisitIDs removes the "page_visits" edge to PageVisit entities by IDs.
func (_u *SessionUpdateOne) RemovePageVisitIDs(ids ...uuid.UUID) *SessionUpdateOne {
	_u.mutation.RemovePageVisitIDs(ids...)
	return _u
}

// RemovePageVisits removes "page_visits" edges to PageVisit entities.
func (_u *SessionUpdateOne) RemovePageVisits(v ...*PageVisit) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePageVisitIDs(ids...)
}

// ClearHighlights clears all "highlights" edges to the Highlight entity.
func (_u *SessionUpdateOne) ClearHighlights() *SessionUpdateOne {
	_u.mutation.ClearHighlights()
	return _u
}

// RemoveHighlightIDs removes the "highlights" edge to Highlight entities by IDs.
func (_u *SessionUpdateOne) RemoveHighlightIDs(ids ...uuid.UUID) *SessionUpdateOne {
	_u.mutation.RemoveHighlightIDs(ids...)
	return _u
}

// RemoveHighlights removes "highlights" edges to Highlight entities.
func (_u *SessionUpdateOne) RemoveHighlights(v ...*Highlight) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHighlightIDs(ids...)
}

// ClearRawEvents clears all "raw_events" edges to the RawEvent entity.
func (_u *SessionUpdateOne) ClearRawEvents() *SessionUpdateOne {
	_u.mutation.ClearRawEvents()
	return _u
}

// RemoveRawEventIDs removes the "raw_events" edge to RawEvent entities by IDs.
func (_u *SessionUpdateOne) RemoveRawEventIDs(ids ...uuid.UUID) *SessionUpdateOne {
	_u.mutation.RemoveRawEventIDs(ids...)
	return _u
}

// RemoveRawEvents removes "raw_events" edges to RawEvent entities.
func (_u *SessionUpdateOne) RemoveRawEvents(v ...*RawEvent) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRawEventIDs(ids...)
}

// ClearMindmap clears the "mindmap" edge to the MindmapGraph entity.
func (_u *SessionUpdateOne) ClearMindmap() *SessionUpdateOne {
	_u.mutation.ClearMindmap()
	return _u
}

// ClearTokenUsage clears all "token_usage" edges to the TokenUsage entity.
func (_u *SessionUpdateOne) ClearTokenUsage() *SessionUpdateOne {
	_u.mutation.ClearTokenUsage()
	return _u
}

// RemoveTokenUsageIDs removes the "token_usage" edge to TokenUsage entities by IDs.
func (_u *SessionUpdateOne) RemoveTokenUsageIDs(ids ...uuid.UUID) *SessionUpdateOne {
	_u.mutation.RemoveTokenUsageIDs(ids...)
	return _u
}

// RemoveTokenUsage removes "token_usage" edges to TokenUsage entities.
func (_u *SessionUpdateOne) RemoveTokenUsage(v ...*TokenUsage) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTokenUsageIDs(ids...)
}

// ClearAiLogs clears all "ai_logs" edges to the AILog entity.
func (_u *SessionUpdateOne) ClearAiLogs() *SessionUpdateOne {
	_u.mutation.ClearAiLogs()
	return _u
}

// RemoveAiLogIDs removes the "ai_logs" edge to AILog entities by IDs.
func (_u *SessionUpdateOne) RemoveAiLogIDs(ids ...uuid.UUID) *SessionUpdateOne {
	_u.mutation.RemoveAiLogIDs(ids...)
	return _u
}

// RemoveAiLogs removes "ai_logs" edges to AILog entities.
func (_u *SessionUpdateOne) RemoveAiLogs(v ...*AILog) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAiLogIDs(ids...)
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Session entity.
func (_u *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := session.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := session.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Session.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionStatus(); ok {
		if err := session.SessionStatusValidator(v); err != nil {
			return &ValidationError{Name: "session_status", err: fmt.Errorf(`ent: validator failed for field "Session.session_status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Session.user"`)
	}
	return nil
}

func (_u *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(session.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(session.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(session.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(session.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(session.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(session.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(session.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(session.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SessionStatus(); ok {
		_spec.SetField(session.FieldSessionStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(session.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(session.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(session.FieldEndedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.UserTable,
			Columns: []string{session.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.UserTable,
			Columns: []string{session.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PageVisitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PageVisitsTable,
			Columns: []string{session.PageVisitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pagevisit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPageVisitsIDs(); len(nodes) > 0 && !_u.mutation.PageVisitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PageVisitsTable,
			Columns: []string{session.PageVisitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pagevisit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PageVisitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PageVisitsTable,
			Columns: []string{session.PageVisitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pagevisit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HighlightsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.HighlightsTable,
			Columns: []string{session.HighlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(highlight.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHighlightsIDs(); len(nodes) > 0 && !_u.mutation.HighlightsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.HighlightsTable,
			Columns: []string{session.HighlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(highlight.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HighlightsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.HighlightsTable,
			Columns: []string{session.HighlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(highlight.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RawEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RawEventsTable,
			Columns: []string{session.RawEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rawevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRawEventsIDs(); len(nodes) > 0 && !_u.mutation.RawEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RawEventsTable,
			Columns: []string{session.RawEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rawevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RawEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RawEventsTable,
			Columns: []string{session.RawEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rawevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MindmapCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.MindmapTable,
			Columns: []string{session.MindmapColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mindmapgraph.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MindmapIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.MindmapTable,
			Columns: []string{session.MindmapColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mindmapgraph.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TokenUsageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.TokenUsageTable,
			Columns: []string{session.TokenUsageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenusage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTokenUsageIDs(); len(nodes) > 0 && !_u.mutation.TokenUsageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.TokenUsageTable,
			Columns: []string{session.TokenUsageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TokenUsageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.TokenUsageTable,
			Columns: []string{session.TokenUsageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AiLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.AiLogsTable,
			Columns: []string{session.AiLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ailog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAiLogsIDs(); len(nodes) > 0 && !_u.mutation.AiLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.AiLogsTable,
			Columns: []string{session.AiLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ailog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AiLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.AiLogsTable,
			Columns: []string{session.AiLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ailog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Session{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
