// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mindhit/api/ent/user"
	"github.com/mindhit/api/ent/usersettings"
)

// UserSettingsCreate is the builder for creating a UserSettings entity.
type UserSettingsCreate struct {
	config
	mutation *UserSettingsMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserSettingsCreate) SetCreatedAt(v time.Time) *UserSettingsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserSettingsCreate) SetNillableCreatedAt(v *time.Time) *UserSettingsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserSettingsCreate) SetUpdatedAt(v time.Time) *UserSettingsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserSettingsCreate) SetNillableUpdatedAt(v *time.Time) *UserSettingsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTheme sets the "theme" field.
func (_c *UserSettingsCreate) SetTheme(v usersettings.Theme) *UserSettingsCreate {
	_c.mutation.SetTheme(v)
	return _c
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_c *UserSettingsCreate) SetNillableTheme(v *usersettings.Theme) *UserSettingsCreate {
	if v != nil {
		_c.SetTheme(*v)
	}
	return _c
}

// SetEmailNotifications sets the "email_notifications" field.
func (_c *UserSettingsCreate) SetEmailNotifications(v bool) *UserSettingsCreate {
	_c.mutation.SetEmailNotifications(v)
	return _c
}

// SetNillableEmailNotifications sets the "email_notifications" field if the given value is not nil.
func (_c *UserSettingsCreate) SetNillableEmailNotifications(v *bool) *UserSettingsCreate {
	if v != nil {
		_c.SetEmailNotifications(*v)
	}
	return _c
}

// SetBrowserNotifications sets the "browser_notifications" field.
func (_c *UserSettingsCreate) SetBrowserNotifications(v bool) *UserSettingsCreate {
	_c.mutation.SetBrowserNotifications(v)
	return _c
}

// SetNillableBrowserNotifications sets the "browser_notifications" field if the given value is not nil.
func (_c *UserSettingsCreate) SetNillableBrowserNotifications(v *bool) *UserSettingsCreate {
	if v != nil {
		_c.SetBrowserNotifications(*v)
	}
	return _c
}

// SetLanguage sets the "language" field.
func (_c *UserSettingsCreate) SetLanguage(v string) *UserSettingsCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *UserSettingsCreate) SetNillableLanguage(v *string) *UserSettingsCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetSessionTimeoutMinutes sets the "session_timeout_minutes" field.
func (_c *UserSettingsCreate) SetSessionTimeoutMinutes(v int) *UserSettingsCreate {
	_c.mutation.SetSessionTimeoutMinutes(v)
	return _c
}

// SetNillableSessionTimeoutMinutes sets the "session_timeout_minutes" field if the given value is not nil.
func (_c *UserSettingsCreate) SetNillableSessionTimeoutMinutes(v *int) *UserSettingsCreate {
	if v != nil {
		_c.SetSessionTimeoutMinutes(*v)
	}
	return _c
}

// SetAutoSummarize sets the "auto_summarize" field.
func (_c *UserSettingsCreate) SetAutoSummarize(v bool) *UserSettingsCreate {
	_c.mutation.SetAutoSummarize(v)
	return _c
}

// SetNillableAutoSummarize sets the "auto_summarize" field if the given value is not nil.
func (_c *UserSettingsCreate) SetNillableAutoSummarize(v *bool) *UserSettingsCreate {
	if v != nil {
		_c.SetAutoSummarize(*v)
	}
	return _c
}

// SetExtensionSettings sets the "extension_settings" field.
func (_c *UserSettingsCreate) SetExtensionSettings(v map[string]interface{}) *UserSettingsCreate {
	_c.mutation.SetExtensionSettings(v)
	return _c
}

// SetID sets the "id" field.
func (_c *UserSettingsCreate) SetID(v uuid.UUID) *UserSettingsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserSettingsCreate) SetNillableID(v *uuid.UUID) *UserSettingsCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *UserSettingsCreate) SetUserID(id uuid.UUID) *UserSettingsCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserSettingsCreate) SetUser(v *User) *UserSettingsCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserSettingsMutation object of the builder.
func (_c *UserSettingsCreate) Mutation() *UserSettingsMutation {
	return _c.mutation
}

// Save creates the UserSettings in the database.
func (_c *UserSettingsCreate) Save(ctx context.Context) (*UserSettings, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserSettingsCreate) SaveX(ctx context.Context) *UserSettings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSettingsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSettingsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserSettingsCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usersettings.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usersettings.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Theme(); !ok {
		v := usersettings.DefaultTheme
		_c.mutation.SetTheme(v)
	}
	if _, ok := _c.mutation.EmailNotifications(); !ok {
		v := usersettings.DefaultEmailNotifications
		_c.mutation.SetEmailNotifications(v)
	}
	if _, ok := _c.mutation.BrowserNotifications(); !ok {
		v := usersettings.DefaultBrowserNotifications
		_c.mutation.SetBrowserNotifications(v)
	}
	if _, ok := _c.mutation.Language(); !ok {
		v := usersettings.DefaultLanguage
		_c.mutation.SetLanguage(v)
	}
	if _, ok := _c.mutation.SessionTimeoutMinutes(); !ok {
		v := usersettings.DefaultSessionTimeoutMinutes
		_c.mutation.SetSessionTimeoutMinutes(v)
	}
	if _, ok := _c.mutation.AutoSummarize(); !ok {
		v := usersettings.DefaultAutoSummarize
		_c.mutation.SetAutoSummarize(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := usersettings.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserSettingsCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserSettings.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserSettings.updated_at"`)}
	}
	if _, ok := _c.mutation.Theme(); !ok {
		return &ValidationError{Name: "theme", err: errors.New(`ent: missing required field "UserSettings.theme"`)}
	}
	if v, ok := _c.mutation.Theme(); ok {
		if err := usersettings.ThemeValidator(v); err != nil {
			return &ValidationError{Name: "theme", err: fmt.Errorf(`ent: validator failed for field "UserSettings.theme": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EmailNotifications(); !ok {
		return &ValidationError{Name: "email_notifications", err: errors.New(`ent: missing required field "UserSettings.email_notifications"`)}
	}
	if _, ok := _c.mutation.BrowserNotifications(); !ok {
		return &ValidationError{Name: "browser_notifications", err: errors.New(`ent: missing required field "UserSettings.browser_notifications"`)}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "UserSettings.language"`)}
	}
	if _, ok := _c.mutation.SessionTimeoutMinutes(); !ok {
		return &ValidationError{Name: "session_timeout_minutes", err: errors.New(`ent: missing required field "UserSettings.session_timeout_minutes"`)}
	}
	if _, ok := _c.mutation.AutoSummarize(); !ok {
		return &ValidationError{Name: "auto_summarize", err: errors.New(`ent: missing required field "UserSettings.auto_summarize"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserSettings.user"`)}
	}
	return nil
}

func (_c *UserSettingsCreate) sqlSave(ctx context.Context) (*UserSettings, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserSettingsCreate) createSpec() (*UserSettings, *sqlgraph.CreateSpec) {
	var (
		_node = &UserSettings{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usersettings.Table, sqlgraph.NewFieldSpec(usersettings.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usersettings.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usersettings.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Theme(); ok {
		_spec.SetField(usersettings.FieldTheme, field.TypeEnum, value)
		_node.Theme = value
	}
	if value, ok := _c.mutation.EmailNotifications(); ok {
		_spec.SetField(usersettings.FieldEmailNotifications, field.TypeBool, value)
		_node.EmailNotifications = value
	}
	if value, ok := _c.mutation.BrowserNotifications(); ok {
		_spec.SetField(usersettings.FieldBrowserNotifications, field.TypeBool, value)
		_node.BrowserNotifications = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(usersettings.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.SessionTimeoutMinutes(); ok {
		_spec.SetField(usersettings.FieldSessionTimeoutMinutes, field.TypeInt, value)
		_node.SessionTimeoutMinutes = value
	}
	if value, ok := _c.mutation.AutoSummarize(); ok {
		_spec.SetField(usersettings.FieldAutoSummarize, field.TypeBool, value)
		_node.AutoSummarize = value
	}
	if value, ok := _c.mutation.ExtensionSettings(); ok {
		_spec.SetField(usersettings.FieldExtensionSettings, field.TypeJSON, value)
		_node.ExtensionSettings = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usersettings.UserTable,
			Columns: []string{usersettings.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_settings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserSettingsCreateBulk is the builder for creating many UserSettings entities in bulk.
type UserSettingsCreateBulk struct {
	config
	err      error
	builders []*UserSettingsCreate
}

// Save creates the UserSettings entities in the database.
func (_c *UserSettingsCreateBulk) Save(ctx context.Context) ([]*UserSettings, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserSettings, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserSettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserSettingsCreateBulk) SaveX(ctx context.Context) []*UserSettings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSettingsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
