import type { MindmapData } from '@/types/mindmap';

export const mockMindmapData: MindmapData = {
  nodes: [
    {
      id: 'core',
      label: '브라우징 세션',
      type: 'core',
      size: 50,
      color: '#F59E0B',
      position: { x: 0, y: 0, z: 0 },
      data: { description: '2024년 12월 31일 세션' },
    },
    {
      id: 'topic-1',
      label: '개발',
      type: 'topic',
      size: 35,
      color: '#3B82F6',
      position: { x: -150, y: 50, z: 30 },
      data: { visitCount: 5 },
    },
    {
      id: 'topic-2',
      label: '디자인',
      type: 'topic',
      size: 30,
      color: '#10B981',
      position: { x: 100, y: -30, z: -50 },
      data: { visitCount: 3 },
    },
    {
      id: 'topic-3',
      label: '뉴스',
      type: 'topic',
      size: 25,
      color: '#EF4444',
      position: { x: 50, y: 120, z: 80 },
      data: { visitCount: 2 },
    },
    {
      id: 'sub-1-1',
      label: 'React',
      type: 'subtopic',
      size: 20,
      color: '#60A5FA',
      position: { x: -220, y: 100, z: 60 },
      data: { visitCount: 3 },
    },
    {
      id: 'sub-1-2',
      label: 'TypeScript',
      type: 'subtopic',
      size: 18,
      color: '#60A5FA',
      position: { x: -200, y: -20, z: 0 },
      data: { visitCount: 2 },
    },
    {
      id: 'sub-2-1',
      label: 'Figma',
      type: 'subtopic',
      size: 22,
      color: '#34D399',
      position: { x: 180, y: -80, z: -30 },
      data: { visitCount: 2 },
    },
    {
      id: 'page-1',
      label: 'React 공식 문서',
      type: 'page',
      size: 12,
      color: '#93C5FD',
      position: { x: -280, y: 150, z: 90 },
      data: { urls: ['https://react.dev'] },
    },
    {
      id: 'page-2',
      label: 'MDN Web Docs',
      type: 'page',
      size: 10,
      color: '#93C5FD',
      position: { x: -250, y: 50, z: 100 },
      data: { urls: ['https://developer.mozilla.org'] },
    },
  ],
  edges: [
    { source: 'core', target: 'topic-1', weight: 1 },
    { source: 'core', target: 'topic-2', weight: 0.8 },
    { source: 'core', target: 'topic-3', weight: 0.5 },
    { source: 'topic-1', target: 'sub-1-1', weight: 0.9 },
    { source: 'topic-1', target: 'sub-1-2', weight: 0.7 },
    { source: 'topic-2', target: 'sub-2-1', weight: 0.8 },
    { source: 'sub-1-1', target: 'page-1', weight: 0.6 },
    { source: 'sub-1-1', target: 'page-2', weight: 0.4 },
  ],
  layout: {
    type: 'galaxy',
    params: {},
  },
};
